apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingassistantservice
  labels:
    app: shoppingassistantservice
    app.kubernetes.io/name: shoppingassistantservice
    app.kubernetes.io/part-of: aws-eks-devsecops-platform
spec:
  selector:
    matchLabels:
      app: shoppingassistantservice
  template:
    metadata:
      labels:
        app: shoppingassistantservice
        app.kubernetes.io/name: shoppingassistantservice
        app.kubernetes.io/part-of: aws-eks-devsecops-platform
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 5
      containers:
        - name: shoppingassistantservice
          image: gcr.io/google-samples/microservices-demo/shoppingassistantservice:v0.10.0
          ports:
            - containerPort: 80
              name: http
          env:
            - name: PORT
              value: "80"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: productcatalogservice:3550
            - name: PROJECT_ID
              value: "online-boutique-dev"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /health
              port: 80
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            httpGet:
              path: /health
              port: 80
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
