# platform/gitops/argocd/applications/falco.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    platform-layer: security
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: platform-project
  source:
    repoURL: https://github.com/dinhtri6905/aws-eks-devsecops-platform.git
    targetRevision: main
    path: platform/gitops/kustomize/security/falco
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m