# platform/gitops/argocd/applications/gatekeeper-install.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-install
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    platform-layer: security
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform-project
  source:
    repoURL: https://github.com/dinhtri6905/aws-eks-devsecops-platform.git
    targetRevision: main
    path: platform/gitops/kustomize/security/opa-gatekeeper/install
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle