apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    platform-layer: security
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform-project
  source:
    repoURL: https://github.com/dinhtri6905/aws-eks-devsecops-platform.git
    targetRevision: main
    path: platform/gitops/kustomize/security/network-policies
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
