apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-admission-create
spec:
  template:
    metadata:
      annotations:
        argocd.argoproj.io/hook: null
        argocd.argoproj.io/hook-delete-policy: null
