apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
    app.kubernetes.io/name: loadgenerator
    app.kubernetes.io/part-of: aws-eks-devsecops-platform
spec:
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
        app.kubernetes.io/name: loadgenerator
        app.kubernetes.io/part-of: aws-eks-devsecops-platform
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      initContainers:
        - name: wait-frontend
          image: busybox:1.35
          command:
            - sh
            - -c
            - until wget -q --spider http://frontend/; do echo waiting for frontend; sleep 3; done
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
      containers:
        - name: main
          image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.10.0
          env:
            - name: FRONTEND_ADDR
              value: "frontend:80"
            - name: USERS
              value: "10"
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
