# platform/gitops/argocd/config/argocd-cm-patch.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd

data:
  resource.customizations.health.templates.gatekeeper.sh_ConstraintTemplate: |
    hs = {}

    if obj.status ~= nil and obj.status.created == true then
      hs.status = "Healthy"
      hs.message = "ConstraintTemplate created successfully"
      return hs
    end

    hs.status = "Progressing"
    hs.message = "Waiting for Gatekeeper to create ConstraintTemplate"
    return hs