apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  # The Root Application watches this directory, which contains
  # the four child Application manifests (App-of-Apps pattern).
  # ArgoCD will create/update/delete those Applications based on
  # what is present here.
  source:
    repoURL: https://github.com/dinhtri6905/aws-eks-devsecops-platform.git
    targetRevision: main
    path: platform/gitops/argocd/applications

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
