apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cartservice
  labels:
    app: cartservice
    app.kubernetes.io/name: cartservice
    app.kubernetes.io/part-of: aws-eks-devsecops-platform
spec:
  selector:
    matchLabels:
      app: cartservice
      app.kubernetes.io/part-of: aws-eks-devsecops-platform
  strategy:
    blueGreen:
      activeService: cartservice-active
      previewService: cartservice-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 300
      prePromotionAnalysis:
        templates:
          - templateName: success-rate-check
        args:
          - name: service-name
            value: cartservice
          - name: pod-template-hash
            valueFrom:
              podTemplateHashValue: Latest
  template:
    metadata:
      labels:
        app: cartservice
        app.kubernetes.io/name: cartservice
        app.kubernetes.io/part-of: aws-eks-devsecops-platform
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 5
      containers:
        - name: cartservice
          image: gcr.io/google-samples/microservices-demo/cartservice:v0.10.0
          ports:
            - containerPort: 7070
              protocol: TCP
              name: grpc
          env:
            - name: REDIS_ADDR
              value: "redis-cart:6379"
            - name: PORT
              value: "7070"
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            grpc:
              port: 7070
              service: ""
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            grpc:
              port: 7070
              service: ""
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]